# Generated by Django 2.2.3 on 2020-03-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_auto_20200312_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='previous_evolution',
            new_name='previous_evolutions',
        ),
    ]
